src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }


    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="user")
     */
    private $notes;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Command::class, mappedBy="user")
     */
    private $commands;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $card_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $card_name;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->commands = new ArrayCollection();
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }


    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Command[]
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setUser($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->removeElement($command)) {
            // set the owning side to null (unless already changed)
            if ($command->getUser() === $this) {
                $command->setUser(null);
            }
        }

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCardNumber(): ?string
    {
        return $this->card_number;
    }

    public function setCardNumber(string $card_number): self
    {
        $this->card_number = $card_number;

        return $this;
    }

    public function getCardName(): ?string
    {
        return $this->card_name;
    }

    public function setCardName(?string $card_name): self
    {
        $this->card_name = $card_name;

        return $this;
    }
}

src/Controller/Front/FrontCartController.php
<?php


namespace App\Controller\Front;


use App\Entity\Command;
use App\Repository\CommandRepository;
use App\Repository\ProductRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;


class FrontCartController extends AbstractController
{

    /**
     * @Route("/cart/", name="cart")
     */
    public function indexCart(SessionInterface $session, ProductRepository $productRepository)
    {
        $panier = $session->get('panier', []);
        $panierWithData = [];
        foreach ($panier as $id => $quantity){
            $panierWithData[] = [
                'product' => $productRepository->find($id),
                'quantity' => $quantity
            ];
        }
        return $this->render('front/panier.html.twig', ['items' => $panierWithData]);
    }

    /**
     * @Route("/cart/add/{id}", name="add_cart")
     */
    public function addCart($id, SessionInterface $session)
    {
        $panier = $session->get('panier', []);

        if(!empty($panier[$id])){
            $panier[$id]++;
        }else{
            $panier[$id] = 1;
        }


        $session->set('panier', $panier);

        return $this->redirectToRoute('front_show_product', ['id' => $id]);
    }

    /**
     * @Route("/cart/delete/{id}", name="delete_cart")
     */
    public function deleteCart($id,SessionInterface $session)
    {
        $panier = $session->get('panier', []);

        if(!empty($panier[$id]) && $panier[$id] == 1 ){
            unset($panier[$id]);
        }else{
            $panier[$id]--;
        }

        $session->set('panier', $panier);

        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/infos/", name="info_cart")
     */
    public function infosCart(UserRepository $userRepository)
    {

        $user = $this->getUser();

        if($user){
            $user_mail = $user->getUserIdentifier();
            $user_true = $userRepository->findBy(['email' => $user_mail]);
            return $this->render('front/infos-cart.html.twig', ['user' => $user_true]);
        }else{
            return $this->render('front/infos-cart.html.twig');
        }

    }

    /**
     * @Route("/command/info/", name="info_command")
     */
    public function infoCommand(SessionInterface $session,
                             ProductRepository $productRepository,
                             UserRepository $userRepository,
                             Request $request,
                             EntityManagerInterface $entityManager,
                             CommandRepository $commandRepository
                             )
    {
        // On récupère le panier qui est enregistré dans la session
        $panier = $session->get('panier', []);
        $p = 0;

        // Pour chaque produit on cherche son prix et on multiplie par la quantité et on l'ajoute
        // à la variable p pour avoir le prix total du panier
        foreach ( $panier as $prod => $quantity){
            $product = $productRepository->find($prod);
            $price_product = $product->getPrice();
            $p = $p + $price_product*$quantity;
        }


        // On récupère le user connecté
        $user = $this->getUser();

        // On récupère toutes les commandes dans un tableau
        $commandall = $commandRepository->findAll();
        // On compte toutes les commandes
        $commandlist = count($commandall);
        // On ajoute + 1 car une commande a été supprimée $number va servir pour number_order de la commande
        $number = $commandlist + 1;
        $date = new \DateTime("NOW") ;

        //On attribue les données à une nouvelle commande
        $command = new Command();
        $command->setNumberOrder('Commd-'.$number);
        $command->setDate($date);
        $command->setPrice($p);

        // On enregistre dans la base de données
        $entityManager->persist($command);
        $entityManager->flush();

        $id = $command->getId();

        // Pour enregistrer les informations dans la table product_command
        foreach ( $panier as $prod => $quantity) {
            // On réalise une requête SQL avec une chaîne de caractères PHP
            // On se connecte au serveur MySQL
            $connexionBdd = mysqli_connect("localhost", "root", "root");
            // ON sélectionne la base de données
            $selectionBdd = mysqli_select_db($connexionBdd, "project_final_piscine");
            // On change le stocke du produit
            $product = $productRepository->find($prod);
            $stock_begin = $product->getStock();
            $stock_end = $stock_begin - $quantity;
            $product->setStock($stock_end);
            // On écrit la requête SQL sous forme de chaîne de caractères PHP
            $requete = "INSERT INTO product_command (product_amount, product_id, command_id) VALUES (" . $quantity . ", " . $product->getId() . ", " . $id . ")";
            // On envoie de la requête depuis le script actuel vers la base de données et on récupère le résultat de la requête
            $resultat = mysqli_query($connexionBdd, $requete);
            // On ferme la connexion au serveur MySQL
            mysqli_close($connexionBdd);

            // On vide le panier
            unset($panier[$prod]);
            $session->set('panier', $panier);

            // On enregistre dans la base de données les changements du produit
            $entityManager->persist($product);
            $entityManager->flush();

        }

        if ($user){
            // Si un user est connecté on l'identifie en récupérant son adresse mail
            $user_mail = $user->getUserIdentifier();
            // On cherche dans la base de donnée à quel user il correspond
            $user_true = $userRepository->findBy(['email' => $user_mail]);



             // On récupère les données du formulaire
            $name = $request->request->get('name');
            $firstname = $request->request->get('firstname');
            $email = $request->request->get('email');
            $adress = $request->request->get('adress');
            $city = $request->request->get('city');
            $zipcode = $request->request->get('zipcode');

            //On attribue au user les données
            $user_true[0]->setEmail($email);
            $user_true[0]->setName($name);
            $user_true[0]->setFirstname($firstname);
            $user_true[0]->setAdress($adress);
            $user_true[0]->setCity($city);
            $user_true[0]->setZipcode($zipcode);

            // On enregistre dans la base de données
            $entityManager->persist($user_true[0]);
            $entityManager->flush();

            // on attribue le user à la command
            $command->setUser($user_true[0]);

            // On enregistre dans la base de données
            $entityManager->persist($command);
            $entityManager->flush();

        }else{
            // Si aucun user n'est connecté
            // les informations sont enregistrées dans la table command

            // Récupération des données du formualire
            $name = $request->request->get('name');
            $firstname = $request->request->get('firstname');
            $email = $request->request->get('email');
            $adress = $request->request->get('adress');
            $city = $request->request->get('city');
            $zipcode = $request->request->get('zipcode');



            //On attribue les données à la commande
            $command->setName($name . " " . $firstname);
            $command->setEmail($email);
            $command->setAdress($adress);
            $command->setCity($city);
            $command->setZipcode($zipcode);

            // On enregistre dans la base de données
            $entityManager->persist($command);
            $entityManager->flush();

        }

        return $this->redirectToRoute('card_infos', ['id' => $id]);

    }

    /**
     * @Route("/cart/card/{id}", name="card_infos")
     */
    public function cardInfos($id, SessionInterface $session, CommandRepository $commandRepository)
    {
        $command = $commandRepository->find($id);
        return $this->render('Front/card_cart.html.twig', ['command' => $command]);
    }

    /**
     * @Route("/cart/mail/{id}", name="mail")
     */
    public function mail($id, UserRepository $userRepository,
                         Request $request,
                         EntityManagerInterface $entityManager,
                         CommandRepository $commandRepository,
                            \Swift_Mailer $mailer)
    {
        // Méthode d'envoi de mail
        $user = $this->getUser();
        $command = $commandRepository->find($id);
        if ($user){
            // Si un user est connecté on récupère ses informations
            $user_mail = $user->getUserIdentifier();
            $user_true = $userRepository->findBy(['email' => $user_mail]);
            $user_true[0]->setCardName($request->request->get('name'));
            $user_true[0]->setCardNumber($request->request->get('number'));
            $entityManager->persist($user_true[0]);
            $entityManager->flush();

            //$command = $commandRepository->findAll();
            //$count = count($command);
            //$command_one = $commandRepository->find($count + 1);

            // Envoi du message
            $message = (new \Swift_Message('Nouvelle commande'))
                // On attribue l'expéditeur
                ->setFrom('superediscount@smail.com')

                // On attribue le destinataire
                ->setTo($user_true[0]->getEmail())

                // On crée le texte avec la vue
                ->setBody(
                    $this->renderView(

templates/Front/_categories_all.html.twig
{% for categorie in categories %}
    <li class="element">{{ categorie.name }}</li>
{% endfor %}

templates/Front/_licences_all.html.twig
{% for licence in licences %}
    <li class="element">{{ licence.name }}</li>
{% endfor %}

templates/Front/_products_all.html.twig
{% for product in products %}
    <li class="element">{{ product.name }}</li>
{% endfor %}

templates/Front/base.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Nicolas SAMPAIO">
    <meta name="description" content="Site de e-commerce sur le super-héros">
    <meta name="keywords" content="super-héros, superman, batman, jouets, jeux vidéos, statuette">
    <link rel="stylesheet" href="{{ asset('style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    {% block link %}{% endblock link %}
    <title>{% block metaTitle %}{% endblock metaTitle %}</title>

</head>
<body>

<header >
    <div class="header">
        <div class="w20">
            <a href="{{ path('front_home') }}">
                Accueil
            </a>
        </div>
        <div class="search">
            <form action="{{ path('front_search') }}" class="form relative" method="get">
                <input class="input" type="search" placeholder="Rechercher..." name="q" id="searchinput">
                <input type="submit" class="button" value="Rechercher">
                <div class="suggestions" id="suggestions"></div>
            </form>
        </div>
        <div class="w40">
            <div class="categories">
                <a href="{{ path('front_categories_list') }}">Catégories</a>
            </div>
            <div class="licences">
                <a href="{{  path('front_list_licence') }}">Licences</a>
            </div>
            <div class="log">
                <a href="{{ path('app_login') }}">
                    {% if app.user %}
                    {{ app.user.firstname }} {{ app.user.name  }}
                    {% endif %}
                    {% if app.user is null %}
                        Se connecter/S'inscrire
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="menuh">
            <ul class="menuhamburger" id="menuhamburger">
                <li class="hambur" id="ham1"></li>
                <li class="hambur" id="ham2"></li>
                <li class="hambur" id="ham3"></li>
            </ul>
        </div>
        <div class="basket">
            <a href="{{ path('cart') }}"><img src="{{ asset('img/logo/panier.png') }}" alt="panier" class="cart"></a>{# path('front_basket') #}
        </div>
    </div>
    <div class="sidebarh" id="sidebarh">
        <a href="{{ path('front_categories_list') }}">Catégories</a>
        <a href="{{  path('front_list_licence') }}">Licences</a>
        <a href="{{ path('app_login') }}">
            {% if app.user %}
                {{ app.user.firstname }} {{ app.user.name  }}
            {% endif %}
            {% if app.user is null %}
                Se connecter/S'inscrire
            {% endif %}</a>
    </div>
</header>

{#
https://symfony.com/doc/3.4/templating/embedding_controllers.html
avec la syntaxe de : https://stackoverflow.com/questions/45396501/how-to-embed-controllers-in-a-template-using-symfony-4-directory-structure
#}
<div class="display-none">
    <ul>
        {{ render(controller('App\\Controller\\Front\\FrontCategoryController::categoriesAll')) }}
        {{ render(controller('App\\Controller\\Front\\FrontProductController::productsAll')) }}
        {{ render(controller('App\\Controller\\Front\\FrontLicenceController::licencesAll')) }}
    </ul>

</div>


<main class="main">
    {% block main %}
    {% endblock main %}
</main>

<footer >
    <div class="footer">
        <div class="info">
            <ul>
                <li class="about">
                    <a href="#">Informations</a>
                </li>
                <li>
                    <a href="#">Carrières</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <div class="up">
            <a href="#top">Retour en haut</a>
        </div>
        <div class="social d-flex justify-content-center">
            <ul class="d-flex justify-content-center align-items-center">
                <li><a href="https://fr-fr.facebook.com/"><img class="facebook" src="{{ asset('img/logo/facebook.png') }}" alt="facebook"></a></li>
                <li><a href="https://www.youtube.com/"><img src="{{ asset('img/logo/youtube.png') }}" alt="youtube"></a></li>
                <li><a href="https://twitter.com/?lang=fr"><img src="{{ asset('img/logo/twitter.png') }}" alt="twitter"></a></li>
            </ul>
        </div>
    </div>
</footer>

<script>
    let menu = document.getElementById('menuhamburger');
    let sidebar = document.getElementById('sidebarh')
    let h1 = document.getElementById("ham1");
    let h2 = document.getElementById("ham2");
    let h3 = document.getElementById("ham3");
    let main = document.querySelector("main");
    let footer = document.querySelector("footer");
    let element = document.querySelectorAll('.element');
    let elements = [];
    let suggestions = document.querySelectorAll(".suggestion");
    element.forEach(data => elements.push(data.innerHTML));
    const searchinput = document.getElementById('searchinput');
    searchinput.addEventListener('keyup', function (){
        const input = searchinput.value;
        const result = elements.filter(item => item.toLocaleLowerCase().includes(input.toLocaleLowerCase()));
        let suggestion = '';
        if(input != ''){
            result.forEach(resultItem =>
                suggestion +=`
        <div class="suggestion" onclick="choice('${resultItem}')">${resultItem}</div>
        `)
        }
            document.getElementById('suggestions').innerHTML = suggestion;
    })

    function choice(data)
    {
        document.getElementById('searchinput').value = data;
    }

    menu.addEventListener('click', () => {
        console.log(sidebar.style.display)
        if(sidebar.style.display === "none" || sidebar.style.display === ""){
            sidebar.style.display = "flex";
            h1.style.transform = "rotate(45deg) translateY(13px)";
            h2.style.opacity = "0";
            h3.style.transform = "rotate(-45deg) translateY(-13px)";
        }else{
            sidebar.style.display = "none";
            h1.style.transform = "rotate(0) translateY(0)";
            h2.style.opacity = "1";
            h3.style.transform = "rotate(0) translateY(0)";
        }

    })
</script>
{% block script %}
{% endblock %}
</body>
</html>

templates/Front/card_cart.html.twig
{% extends 'front/base.html.twig' %}


{% block main %}
    <div class="container">
        <div class="total">
            <h1>Total</h1>
            <h2>{{ command.price }} €</h2>
        </div>
        <form action="{{ path('mail', {'id' : command.id}) }}" class="form" method="post">
            <label for="name" class="label-media">Nom sur la carte</label>
            <input type="text" placeholder="Roger Le Tavernier" class="input-product" name="name"
                    {% if app.user %} {% if app.user.cardName is not null %}value="{{ app.user.cardName }}" {% endif %}  {% endif %}>
            <p class="line-1"></p>
            <label for="number" class="label-media">Numéro de la carte</label>
            <input type="text" placeholder="1234 5678 9012 3456" class="input-product" name="number"
                   {% if app.user %}{% if app.user.cardNumber is not null %}value="{{ app.user.cardNumber }}" {% endif %}{% endif %} >
            <p class="line-2"></p>
            <label for="code" class="label-media">Code de sécurité</label>
            <input type="text" placeholder="12345" class="input-product" name="code">
            <input type="submit" value="Payer" class="button-product">
        </form>
    </div>
{% endblock %}

templates/Front/categories.html.twig
{% extends 'front/base.html.twig' %}

{% block main %}

    <div class="container">
        {% for categorie in categories %}
            <div class="card br">
                <a href="{{ path('front_categorie_show', {'id' : categorie.id}) }}"><img src="{{ asset('img/media/' ~ categorie.media) }}" alt="{{ categorie.name }}"></a>
                <h1>
                    <a href="{{ path('front_categorie_show', {'id' : categorie.id}) }}">{{ categorie.name }}</a>
                </h1>
                <h2>
                    {{ categorie.description }}
                </h2>
            </div>
        {% endfor %}
    </div>
    <div class="page">
        {{ knp_pagination_render(categories) }}
    </div>

{% endblock %}

templates/Front/category.html.twig
{% extends 'front/base.html.twig' %}

{% block main %}
    <div class="container-category">
        <h1>
            {{ category.name }}
        </h1>
        <h2 class="block">
            {{ category.description }}
        </h2>
    </div>
    <div class="container">
        {% for product  in category.products %}
            <div class="card">
                <a href="{{ path('front_show_product', {'id' : product.id}) }}"><img src="{{ asset('img/media/' ~ product.media[0].src) }}" alt="{{ product.media[0].alt }}" class="w60"></a>
                <h3><a href="{{ path('front_show_product', {'id' : product.id}) }}">{{ product.name }}</a></h3>
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/Front/infos-cart.html.twig
{% extends 'front/base.html.twig' %}

{% block main %}
    <div class="container">
        <h2>Informations pour la livraison</h2>

        <form action="{{ path('info_command') }}" method="post">
            <div class="margin-top">
                <label for="name">Votre nom</label>
                <input type="text" id="name" name="name" class="input" {% if app.user %} value="{{ app.user.name}}"{% endif %}>
            </div>
            <div class="margin-top">
                <label for="firstname">Votre prénom</label>
                <input type="text" id="firstname" name="firstname" class="input" {% if app.user %} value="{{ app.user.firstname}}"{% endif %}>
            </div>
            <div class="margin-top">
                <label for="email">Votre email</label>
                <input type="text" id="email" name="email" class="input" {% if app.user %} value="{{ app.user.email}}"{% endif %}>
            </div>
            <div class="margin-top">
                <label for="adress">Votre adresse</label>
                <input type="text" id="adress" name="adress" class="input" {% if app.user %} value="{{ app.user.adress}}"{% endif %}>
            </div>
            <div class="margin-top">
                <label for="city">Votre ville</label>
                <input type="text" id="city" name="city" class="input" {% if app.user %} value="{{ app.user.city}}"{% endif %}>
            </div>
            <div class="margin-top">
                <label for="zipcode">Votre code postal</label>
                <input type="text" id="zipcode" name="zipcode" class="input" {% if app.user %} value="{{ app.user.zipcode}}"{% endif %}>
            </div>
            <div class="margin-top">
                <input type="submit" value="Confirmer" class="button-product">
            </div>
        </form>
    </div>
{% endblock %}

templates/Front/licence.html.twig
{% extends 'front/base.html.twig' %}

{% block main %}
    <div class="container">
        <img src="{{ asset('img/media/' ~  licence.media ) }}" alt="" class="logo">
        <h1>
            {{ licence.name }}
        </h1>
        <h2>
            {{ licence.description }}
        </h2>
    </div>
    <div class="container">
        {% for product  in products %}
            <div class="card">
                <a href="{{ path('front_show_product', {'id' : product.id}) }}"><img src="{{ asset('img/media/' ~ product.media[0].src) }}" alt="{{ product.media[0].alt }}" class="w60"></a>
                <h3><a href="{{ path('front_show_product', {'id' : product.id}) }}">{{ product.name }}</a></h3>
            </div>
        {% endfor %}
        <div class="page">
            {{ knp_pagination_render(products) }}
        </div>
    </div>
{% endblock %}

templates/Front/licences.html.twig
{% extends 'front/base.html.twig' %}

{% block main %}
    <div class="container">
        {% for licence in licences %}
            <div class="card br">
                <a href="{{ path('front_show_licence', {'id' : licence.id}) }}"><img src="{{ asset('img/media/' ~  licence.media ) }}"></a>
                <h1>
                    <a href="{{ path('front_show_licence', {'id' : licence.id}) }}">{{ licence.name }}</a>
                </h1>
                <h2>
                    {{ licence.description }}
                </h2>
            </div>

    {% endfor %}
    </div>
{% endblock %}

templates/Front/mail.html.twig
<h1>Votre commande</h1>
<p>Nom : {% if command.user %}{{command.user.name}} {{ command.user.firstname }}{% else %}{{ command.name }}{% endif %}</p>
<p>e-mail : {% if command.user %}{{command.user.email}}{% else %}{{ command.email }}{% endif %}</p>
<p>Montant : {{command.price}} €</p>